#language: python
#python:
#  - "3.5"
#  - "3.6"
#
#install: pip install -r requirements.txt
#
#before_install:
#  - "pip install -U pip"
#  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
language: python
python:
  - '3.5'
  - '3.6'

install: pip install tox-travis
script: tox

branches:
  only:
  - master

stages:
  - lint
  - test
jobs:
  include:
    - { stage: lint, python: 3.5, env: TOXENV=flake8 }
    - { stage: lint, python: 3.6, env: TOXENV=flake8 }
      script: skip
