language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install: pip install -r requirements.txt

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"


 # Requirements for running the package
 install: pip install -r requirements.txt
