language: python
python:
- '3.5'
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
notifications:
  webhooks:
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
    if: branch = master
    urls:
      secure: Cbhi9Tv9DhM+ah8xjm5/YG6wBXEPn3VjVMlduD5DevJIyUtGa3kyDtcjHnYx8SYMWtHBhAS2RWAbZ1RNktCQDNUkkCQDCnL+zeASkBNdFpDNWsbIEjyOXHjt01x/gljrhRS7Gg9deiQNQdHyztccjIFHu9q+jh8A2DqG6FMytKEMC+i/lYcreN475P8ofiyfcT8TrPDxz14UE6xiQth4ba2jp0a3vxw/klMuzBQgVJhkndepqJTl28WBtZCA8KMQlTyNjTrXLV8zRVbajp1DTScOJtfHe1okB3CXGRbtb59fBzuAAXMH7TWjTqSrqaDGnwdlWIdJgzZi7lNz+YfxMg9pon6kCWsR8VmtM1rJ2roUw7E3J+qpoZHFQJm36NeMPO1rkXzRKAfGLNimB9PHxDmf3uKXgppLFsnzdFKTwvNneATh6Cn77tJxNWN4XI7d5bnIvzoNTLNq2Ik5pWnrJuQLTuRAM1PqXoR9sNVCQ9O0GNfyAr/MdngblyyueddbTKZ/+A0ICRayEnfJ6b8BlUSGihYdGY2BYDrTQsBUwdmnVZwvHucK1GcD/IyaJNu/Gj4/+Um0fG6B9Ps670wFqia35ZXKNUMOYIAL9VabZBfhr2U040yD4sBWugFkr7wWHMcqFy/W1CAeBW7ZzMEaQQGXdBNJquU3OFi1l/Ym+V8=
      # deploy to appuio.ch
