dist: xenial
sudo: required

language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'

stages:
  - lint
  - test

jobs:
  include:
    - { stage: lint, python: 3.6, env: TOXENV=flake8 }
    - { stage: lint, python: 3.6, env: TOXENV=pylint }

install: pip install tox-travis
script: tox
