language: python
python:
- '3.5'
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
notifications:
  webhooks:
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
    if: branch = master
    urls:
      secure: K7wIEsRFw749QLnSRACmGnL+h7/Gmqf2sqrjVo1gXtcnR2fCRC++/jA8rtyJpUMGCxcVQQYXHIVwo3EKG/hbJ9o0fj3VALZpWl7VVAw39TEEuYtWtW6tqROR+X2dygoM6EXpo55aVl0z1o993iO6hRoeDvJ85/K5kmi6jcRVFqNic/oLsACn6XmHbX0FgVMg5ijsGSuwNSzCNVPqj0sdmZgWoODOfStj3wfl9/GRbxxB9jns5Hdx/3qgA9S8YAGhua8eTVBaiGVEkzq+/8Q8J7rhW4VhxNvUKp+Hg5z1+ApQ8YqSTrV2dBxDlNR6Uoh4FBLDWYhSd01bAC0nzl/NbpwR0HTiSZT1m7oMqnrQm5OxKhRJRGr/tHYSBpkusyangrImWcWKJSWCM25Syu7DMiJUYXZBf0Za/X1huy8bWN601fUhuM4zEGOHTRbFQvotsViNx+JTgdQ+8c97RHGweb0cbsskk5L9fc5TiiBrNcYTpwPIgKBlEF+xztnJreEx4NV43Lg9Jhzv17TYon6te6vNBo+5rEsQImRSSdka9jzzwhMUiCEnIylTlNY+x8EIieDo4tWthbmIAMBEkEJV+PiLcdjsubN9wP0Jozn4hPWrr6npfMKhPJFdqa1FZmscpYZqx5/3HbzvLCrSRUK1lX3nSfDOfbyFJOOsZ2asMPw=
